title: Chatty Webviews Documentation
description: Documentation page for the Chatty Webviews framework
remote_theme: pmarsceill/just-the-docs

url: https://chattywebviews.github.io/

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
